//! Differential test: quaternions and poses against OctoMap C++ 1.10.0.
//!
//! The fixture is generated by `scripts/gen_golden_pose.cpp`. Everything is
//! compared as raw IEEE-754 bit patterns — the reference derives Euler angles
//! by building a rotation matrix and running `atan2` over it, and a shorter
//! half-angle formula would agree to several decimals while disagreeing here.

// The angle literals below are truncated approximations of pi and pi/2 — and
// have to be. They are copied verbatim from scripts/gen_golden_pose.cpp, and
// substituting `std::f64::consts::PI` would feed a different value into
// from_euler than the reference received, breaking every bit comparison here.
#![allow(clippy::approx_constant)]

use octomap_core::{Point3, Pose6, Quaternion};

const GOLDEN: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../tests/golden/pose.csv"
));

/// Euler triples the reference used, in the same order.
const EULER: &[(f64, f64, f64)] = &[
    (0.0, 0.0, 0.0),
    (0.3, 0.0, 0.0),
    (0.0, 0.4, 0.0),
    (0.0, 0.0, 0.5),
    (0.3, -0.4, 0.5),
    (-1.0, 0.2, 2.0),
    (1.570_796_3, 0.0, 0.0),
    (0.0, 1.570_796_3, 0.0),
    (0.0, 0.0, 3.141_592_65),
    (2.5, -1.4, 0.7),
    (-2.9, 1.5, -3.0),
    (0.1, 1.5707, 0.1),
];

const VECTORS: &[[f32; 3]] = &[
    [1.0, 0.0, 0.0],
    [0.0, 1.0, 0.0],
    [0.0, 0.0, 1.0],
    [1.0, 2.0, 3.0],
    [-4.5, 0.25, 7.5],
    [0.001, -0.002, 0.003],
];

const POSE_TRANS: &[[f32; 3]] = &[
    [0.0, 0.0, 0.0],
    [1.0, -2.0, 0.5],
    [10.0, 0.0, 0.0],
    [-3.25, 4.5, -1.75],
];

const POSE_ROTS: &[(f64, f64, f64)] = &[
    (0.0, 0.0, 0.0),
    (0.3, -0.4, 0.5),
    (0.0, 0.0, 1.570_796_3),
    (1.0, 0.5, -2.0),
];

fn rows(section: &str) -> Vec<Vec<&'static str>> {
    GOLDEN
        .lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .map(|l| l.split(',').collect::<Vec<_>>())
        .filter(|f| f[0] == section)
        .collect()
}

fn num(s: &str) -> i64 {
    s.parse()
        .unwrap_or_else(|e| panic!("{s:?} is not a number: {e}"))
}

fn bits(s: &str) -> u32 {
    num(s) as u32
}

fn quat_bits(q: &Quaternion) -> [u32; 4] {
    [q.u.to_bits(), q.x.to_bits(), q.y.to_bits(), q.z.to_bits()]
}

fn point_bits(p: Point3) -> [u32; 3] {
    [p.x.to_bits(), p.y.to_bits(), p.z.to_bits()]
}

fn pose(index: usize) -> Pose6 {
    let t = POSE_TRANS[index];
    let (r, p, y) = POSE_ROTS[index];
    Pose6::from_euler(t[0], t[1], t[2], r, p, y)
}

#[test]
fn golden_fixture_is_present_and_populated() {
    assert_eq!(rows("quat").len(), EULER.len());
    assert_eq!(rows("rotate").len(), EULER.len() * VECTORS.len());
    assert_eq!(rows("pose").len(), POSE_TRANS.len());
    assert_eq!(rows("compose").len(), POSE_TRANS.len() * POSE_TRANS.len());
}

#[test]
fn euler_to_quaternion_matches_reference() {
    for row in rows("quat") {
        let i = num(row[1]) as usize;
        let (r, p, y) = EULER[i];
        let q = Quaternion::from_euler(r, p, y);
        assert_eq!(
            quat_bits(&q),
            [bits(row[2]), bits(row[3]), bits(row[4]), bits(row[5])],
            "from_euler({r}, {p}, {y}) diverged: got {q:?}"
        );
    }
}

#[test]
fn quaternion_to_euler_matches_reference() {
    for row in rows("quat") {
        let i = num(row[1]) as usize;
        let (r, p, y) = EULER[i];
        let q = Quaternion::from_euler(r, p, y);
        let (rr, pp, yy) = q.to_euler();
        assert_eq!(
            [rr.to_bits(), pp.to_bits(), yy.to_bits()],
            [bits(row[6]), bits(row[7]), bits(row[8])],
            "to_euler for ({r}, {p}, {y}) diverged: got ({rr}, {pp}, {yy})"
        );
    }
}

#[test]
fn the_euler_cases_include_a_negative_zero() {
    // quat,0 records pitch as bit pattern 2147483648, which is -0.0. atan2(-0,
    // 1) produces it, and comparing bits rather than values is what keeps this
    // visible — `-0.0 == 0.0` would hide a sign flip elsewhere.
    let row = rows("quat").into_iter().find(|f| num(f[1]) == 0).unwrap();
    assert_eq!(bits(row[7]), (-0.0f32).to_bits());

    let (rr, pp, yy) = Quaternion::from_euler(0.0, 0.0, 0.0).to_euler();
    assert_eq!(pp.to_bits(), (-0.0f32).to_bits());
    assert_eq!(rr, 0.0);
    assert_eq!(yy, 0.0);
}

#[test]
fn rotation_matches_reference() {
    let mut compared = 0usize;
    for row in rows("rotate") {
        let qi = num(row[1]) as usize;
        let vi = num(row[2]) as usize;
        let (r, p, y) = EULER[qi];
        let q = Quaternion::from_euler(r, p, y);
        let v = Point3::new(VECTORS[vi][0], VECTORS[vi][1], VECTORS[vi][2]);

        let got = q.rotate(v);
        assert_eq!(
            point_bits(got),
            [bits(row[3]), bits(row[4]), bits(row[5])],
            "rotate of {v:?} by euler ({r}, {p}, {y}) diverged: got {got:?}"
        );
        compared += 1;
    }
    assert_eq!(compared, EULER.len() * VECTORS.len());
}

#[test]
fn axis_angle_matches_reference() {
    let angles = [0.0, 0.5, 1.570_796_3, 3.141_592_65, -0.9];
    let axes: [[f32; 3]; 5] = [
        [0.0, 0.0, 1.0],
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.577, 0.577, 0.577],
        [1.0, 2.0, 3.0],
    ];

    for row in rows("axisangle") {
        let i = num(row[1]) as usize;
        let axis = Point3::new(axes[i][0], axes[i][1], axes[i][2]);
        let q = Quaternion::from_axis_angle(axis, angles[i]);
        assert_eq!(
            quat_bits(&q),
            [bits(row[2]), bits(row[3]), bits(row[4]), bits(row[5])],
            "from_axis_angle({axis:?}, {}) diverged",
            angles[i]
        );
    }
}

#[test]
fn pose_construction_matches_reference() {
    for row in rows("pose") {
        let i = num(row[1]) as usize;
        let p = pose(i);
        assert_eq!(
            point_bits(p.translation),
            [bits(row[2]), bits(row[3]), bits(row[4])],
            "pose {i} translation"
        );
        assert_eq!(
            quat_bits(&p.rotation),
            [bits(row[5]), bits(row[6]), bits(row[7]), bits(row[8])],
            "pose {i} rotation"
        );
    }
}

#[test]
fn pose_transform_matches_reference() {
    let mut compared = 0usize;
    for row in rows("transform") {
        let pi = num(row[1]) as usize;
        let vi = num(row[2]) as usize;
        let v = Point3::new(VECTORS[vi][0], VECTORS[vi][1], VECTORS[vi][2]);

        let got = pose(pi).transform(v);
        assert_eq!(
            point_bits(got),
            [bits(row[3]), bits(row[4]), bits(row[5])],
            "pose {pi} transform of {v:?} diverged: got {got:?}"
        );
        compared += 1;
    }
    assert_eq!(compared, POSE_TRANS.len() * VECTORS.len());
}

#[test]
fn pose_inverse_matches_reference() {
    for row in rows("inv") {
        let i = num(row[1]) as usize;
        let inv = pose(i).inv();
        assert_eq!(
            point_bits(inv.translation),
            [bits(row[2]), bits(row[3]), bits(row[4])],
            "pose {i} inverse translation"
        );
        assert_eq!(
            quat_bits(&inv.rotation),
            [bits(row[5]), bits(row[6]), bits(row[7]), bits(row[8])],
            "pose {i} inverse rotation"
        );
    }
}

#[test]
fn pose_composition_matches_reference() {
    let mut compared = 0usize;
    for row in rows("compose") {
        let a = num(row[1]) as usize;
        let b = num(row[2]) as usize;
        let c = pose(a) * pose(b);

        assert_eq!(
            point_bits(c.translation),
            [bits(row[3]), bits(row[4]), bits(row[5])],
            "pose {a} * pose {b} translation"
        );
        assert_eq!(
            quat_bits(&c.rotation),
            [bits(row[6]), bits(row[7]), bits(row[8]), bits(row[9])],
            "pose {a} * pose {b} rotation"
        );
        compared += 1;
    }
    assert_eq!(compared, POSE_TRANS.len() * POSE_TRANS.len());
}

#[test]
fn the_fixture_covers_rotations_that_actually_rotate() {
    // Guards the comparisons above: an all-identity fixture would pass while
    // testing nothing.
    let nontrivial = rows("quat")
        .iter()
        .filter(|r| bits(r[3]) != 0 || bits(r[4]) != 0 || bits(r[5]) != 0)
        .count();
    assert!(nontrivial >= 10, "only {nontrivial} non-identity rotations");
}
