//! Differential test: every conversion in `TreeGeometry` against output
//! captured from OctoMap C++ 1.10.0.
//!
//! The fixture is generated by `scripts/gen_golden_geometry.cpp` — see
//! `scripts/README.md`. Comparisons are **exact**: both sides perform the same
//! sequence of IEEE-754 operations, so any difference is a real divergence, not
//! rounding noise. Loosening these into approximate comparisons would hide
//! precisely the bugs this test exists to catch.

use octomap_core::{OcTreeKey, TreeGeometry};

const GOLDEN: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../tests/golden/geometry.csv"
));

/// One parsed CSV row, minus comment lines.
struct Row<'a> {
    fields: Vec<&'a str>,
}

impl<'a> Row<'a> {
    fn str(&self, i: usize) -> &'a str {
        self.fields[i]
    }

    fn f64(&self, i: usize) -> f64 {
        self.fields[i]
            .parse()
            .unwrap_or_else(|e| panic!("field {i} ({:?}) is not f64: {e}", self.fields[i]))
    }

    fn u32(&self, i: usize) -> u32 {
        self.fields[i]
            .parse()
            .unwrap_or_else(|e| panic!("field {i} ({:?}) is not u32: {e}", self.fields[i]))
    }
}

fn rows(section: &str) -> Vec<Row<'static>> {
    GOLDEN
        .lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .map(|l| Row {
            fields: l.split(',').collect(),
        })
        .filter(|r| r.str(0) == section)
        .collect()
}

#[test]
fn golden_fixture_is_present_and_populated() {
    // A silently empty fixture would make every test below vacuously pass.
    assert!(
        GOLDEN.lines().count() > 100,
        "golden fixture looks truncated: {} lines",
        GOLDEN.lines().count()
    );
    for section in [
        "coord_to_key",
        "coord_to_key_depth",
        "checked",
        "node_size",
        "sensor",
    ] {
        assert!(
            !rows(section).is_empty(),
            "section {section:?} missing from the golden fixture"
        );
    }
}

#[test]
fn coord_to_key_matches_reference() {
    let mut checked = 0usize;
    for row in rows("coord_to_key") {
        let (res, coord, want_key, want_center) = (row.f64(1), row.f64(2), row.u32(3), row.f64(4));
        let g = TreeGeometry::new(res).unwrap();

        let got_key = g.coord_to_key_axis(coord);
        assert_eq!(
            u32::from(got_key),
            want_key,
            "coord_to_key_axis({coord}) at resolution {res}"
        );

        let got_center = g.key_to_coord_axis(got_key);
        assert_eq!(
            got_center, want_center,
            "key_to_coord_axis({got_key}) at resolution {res}"
        );
        checked += 1;
    }
    assert!(checked >= 80, "only {checked} rows compared");
}

#[test]
fn coord_to_key_at_depth_matches_reference() {
    let mut checked = 0usize;
    for row in rows("coord_to_key_depth") {
        let res = row.f64(1);
        let coord = row.f64(2);
        let depth = row.u32(3);
        let want_key_at_depth = row.u32(4);
        let want_adjusted = row.u32(5);
        let want_center = row.f64(6);
        let g = TreeGeometry::new(res).unwrap();

        let got = g.coord_to_key_axis_at_depth(coord, depth).unwrap();
        assert_eq!(
            u32::from(got),
            want_key_at_depth,
            "coord_to_key_axis_at_depth({coord}, {depth}) at resolution {res}"
        );

        let bottom = g.coord_to_key_axis(coord);
        let got_adjusted = g.adjust_key_axis_at_depth(bottom, depth).unwrap();
        assert_eq!(
            u32::from(got_adjusted),
            want_adjusted,
            "adjust_key_axis_at_depth({bottom}, {depth}) at resolution {res}"
        );

        let got_center = g.key_to_coord_axis_at_depth(got, depth).unwrap();
        assert_eq!(
            got_center, want_center,
            "key_to_coord_axis_at_depth({got}, {depth}) at resolution {res}"
        );
        checked += 1;
    }
    assert!(checked >= 500, "only {checked} rows compared");
}

#[test]
fn bounds_checking_matches_reference() {
    let mut accepted = 0usize;
    let mut rejected = 0usize;
    for row in rows("checked") {
        let (res, coord, valid, want_key) = (row.f64(1), row.f64(2), row.u32(3), row.u32(4));
        let g = TreeGeometry::new(res).unwrap();

        match g.coord_to_key_axis_checked(coord) {
            Some(key) => {
                assert_eq!(valid, 1, "Rust accepted {coord} at {res}, C++ rejected it");
                assert_eq!(u32::from(key), want_key, "checked key for {coord} at {res}");
                accepted += 1;
            }
            None => {
                assert_eq!(valid, 0, "Rust rejected {coord} at {res}, C++ accepted it");
                rejected += 1;
            }
        }
    }
    // Both outcomes must actually occur, or the test is only exercising one arm.
    assert!(
        accepted > 0 && rejected > 0,
        "{accepted} in, {rejected} out"
    );
}

#[test]
fn node_size_matches_reference() {
    for row in rows("node_size") {
        let (res, depth, want) = (row.f64(1), row.u32(2), row.f64(3));
        let g = TreeGeometry::new(res).unwrap();
        assert_eq!(
            g.node_size(depth),
            want,
            "node_size({depth}) at resolution {res}"
        );
    }
}

#[test]
fn three_axis_conversion_matches_per_axis_reference() {
    // The per-axis rows above are the authority; this confirms the Point3
    // wrappers do not reorder or drop an axis. f32 storage in Point3 means only
    // coordinates exactly representable as f32 are valid probes here.
    let g = TreeGeometry::new(0.1).unwrap();
    let probe = [1.25f32, -0.5, 2.0];

    let key = g.coord_to_key(probe.into());
    assert_eq!(
        key,
        OcTreeKey::new(
            g.coord_to_key_axis(f64::from(probe[0])),
            g.coord_to_key_axis(f64::from(probe[1])),
            g.coord_to_key_axis(f64::from(probe[2])),
        )
    );
}

/// The sensor-model defaults are Phase 4 work; capturing the exact reference
/// log-odds now means the implementation has a target instead of a re-derivation.
#[test]
fn sensor_defaults_are_captured_for_phase_4() {
    let mut seen = std::collections::HashMap::new();
    for row in rows("sensor") {
        seen.insert(row.str(1).to_string(), row.f64(2));
    }

    // Exact f32-rounded log-odds the reference stores, not the textbook values.
    assert_eq!(seen["prob_hit_log"], 0.847_297_847_270_965_6);
    assert_eq!(seen["prob_miss_log"], -0.405_465_096_235_275_27);
    assert_eq!(seen["occ_thres_log"], 0.0);
    assert_eq!(seen["clamping_min_log"], -2.000_027_894_973_755);
    assert_eq!(seen["clamping_max_log"], 3.511_030_673_980_713);
}
