//! Differential test: ray traversal, ray casting and point-cloud integration
//! against OctoMap C++ 1.10.0.
//!
//! The fixture is generated by `scripts/gen_golden_ray.cpp`. DDA key sequences
//! are compared element by element — a traversal that visits the same voxels in
//! a different order, or slips by one at a voxel boundary, fails here.
//! Coordinates and log-odds are compared as raw IEEE-754 bit patterns.

use octomap_core::{KeyRay, OcTree, OcTreeKey, Point3, PointCloud};

const GOLDEN: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../tests/golden/ray.csv"
));

fn rows(section: &str) -> Vec<Vec<&'static str>> {
    GOLDEN
        .lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .map(|l| l.split(',').collect::<Vec<_>>())
        .filter(|f| f[0] == section)
        .collect()
}

fn num(s: &str) -> i64 {
    s.parse()
        .unwrap_or_else(|e| panic!("{s:?} is not a number: {e}"))
}

fn f32_from_bits(s: &str) -> f32 {
    f32::from_bits(num(s) as u32)
}

/// The ray endpoints the reference used, keyed by case name.
const RAY_CASES: &[(&str, [f32; 3], [f32; 3])] = &[
    ("same_voxel", [0.01, 0.01, 0.01], [0.02, 0.02, 0.02]),
    ("axis_x", [0.05, 0.05, 0.05], [1.05, 0.05, 0.05]),
    ("axis_x_neg", [0.05, 0.05, 0.05], [-1.05, 0.05, 0.05]),
    ("axis_y", [0.05, 0.05, 0.05], [0.05, 2.05, 0.05]),
    ("axis_z_neg", [0.05, 0.05, 0.05], [0.05, 0.05, -2.05]),
    ("diagonal", [0.05, 0.05, 0.05], [1.05, 1.05, 1.05]),
    ("oblique", [0.05, 0.05, 0.05], [1.05, 0.35, -0.25]),
    ("oblique_reversed", [1.05, 0.35, -0.25], [0.05, 0.05, 0.05]),
    ("corner_graze", [0.0, 0.0, 0.0], [1.0, 1.0, 0.0]),
    ("through_origin", [-0.85, -0.35, -0.15], [0.95, 0.45, 0.25]),
    ("tiny", [0.05, 0.05, 0.05], [0.16, 0.05, 0.05]),
    ("long", [-20.05, -5.05, 3.05], [25.05, 8.05, -4.05]),
];

/// A cast case: name, origin, direction, `ignore_unknown`, `max_range`.
type CastCase = (&'static str, [f32; 3], [f32; 3], bool, f64);

/// The cast cases the reference recorded.
const CAST_CASES: &[CastCase] = &[
    ("hit_ahead", [0.05, 0.05, 0.05], [1.0, 0.0, 0.0], true, -1.0),
    (
        "hit_ahead_strict",
        [0.05, 0.05, 0.05],
        [1.0, 0.0, 0.0],
        false,
        -1.0,
    ),
    (
        "unknown_sideways",
        [0.05, 0.05, 0.05],
        [0.0, 1.0, 0.0],
        false,
        -1.0,
    ),
    (
        "unknown_sideways_ignored",
        [0.05, 0.05, 0.05],
        [0.0, 1.0, 0.0],
        true,
        5.0,
    ),
    (
        "max_range_short",
        [0.05, 0.05, 0.05],
        [1.0, 0.0, 0.0],
        true,
        0.5,
    ),
    ("backwards", [0.05, 0.05, 0.05], [-1.0, 0.0, 0.0], true, 3.0),
    (
        "diagonal_cast",
        [0.05, 0.05, 0.05],
        [1.0, 1.0, 0.0],
        true,
        5.0,
    ),
    (
        "from_obstacle",
        [2.05, 0.05, 0.05],
        [1.0, 0.0, 0.0],
        true,
        -1.0,
    ),
];

const SCAN: &[[f32; 3]] = &[
    [1.05, 0.05, 0.05],
    [0.05, 1.05, 0.05],
    [0.05, 0.05, 1.05],
    [1.05, 1.05, 1.05],
    [-1.05, -0.35, 0.45],
    [2.01, 0.05, 0.05],
    [2.05, 0.05, 0.05],
    [2.09, 0.05, 0.05],
];

const ORIGIN: [f32; 3] = [0.05, 0.05, 0.05];

fn p(v: [f32; 3]) -> Point3 {
    Point3::new(v[0], v[1], v[2])
}

fn scan() -> PointCloud {
    SCAN.iter().map(|&v| p(v)).collect()
}

/// `(ok, key_count)` the reference recorded for a ray case.
fn golden_ray_meta(name: &str) -> (bool, usize) {
    let row = rows("raymeta")
        .into_iter()
        .find(|f| f[1] == name)
        .unwrap_or_else(|| panic!("no raymeta row for {name:?}"));
    (num(row[2]) == 1, num(row[3]) as usize)
}

fn golden_ray_keys(name: &str) -> Vec<OcTreeKey> {
    let mut rows: Vec<_> = rows("ray").into_iter().filter(|f| f[1] == name).collect();
    rows.sort_by_key(|f| num(f[2]));
    rows.iter()
        .map(|f| OcTreeKey::new(num(f[3]) as u16, num(f[4]) as u16, num(f[5]) as u16))
        .collect()
}

fn golden_counts(stage: &str) -> (usize, usize) {
    let row = rows("counts")
        .into_iter()
        .find(|f| f[1] == stage)
        .unwrap_or_else(|| panic!("no counts row for stage {stage:?}"));
    (num(row[2]) as usize, num(row[3]) as usize)
}

fn golden_leaves(stage: &str) -> Vec<(OcTreeKey, u32, u32)> {
    let mut rows: Vec<_> = rows("leaf").into_iter().filter(|f| f[1] == stage).collect();
    rows.sort_by_key(|f| num(f[2]));
    rows.iter()
        .map(|f| {
            (
                OcTreeKey::new(num(f[3]) as u16, num(f[4]) as u16, num(f[5]) as u16),
                num(f[6]) as u32,
                num(f[7]) as u32,
            )
        })
        .collect()
}

fn actual_leaves(tree: &OcTree) -> Vec<(OcTreeKey, u32, u32)> {
    tree.iter_leaves()
        .map(|v| (v.key(), v.depth(), v.value().log_odds.to_bits()))
        .collect()
}

fn assert_counts(tree: &OcTree, stage: &str) {
    let (size, leaves) = golden_counts(stage);
    assert_eq!(tree.len(), size, "node count at stage {stage:?}");
    assert_eq!(
        tree.count_leaf_nodes(),
        leaves,
        "leaf count at stage {stage:?}"
    );
    assert_eq!(tree.count_nodes(), tree.len(), "count drifted at {stage:?}");
}

/// The scene the reference cast rays against: a wall at x = 2.05 with a cleared
/// corridor leading to it.
fn cast_scene() -> OcTree {
    let mut tree = OcTree::new(0.1).unwrap();
    for dy in -3..=3i32 {
        for dz in -3..=3i32 {
            tree.update_node_at(
                Point3::new(2.05, 0.05 + 0.1 * dy as f32, 0.05 + 0.1 * dz as f32),
                true,
            );
        }
    }
    let mut corridor = KeyRay::new();
    tree.compute_ray_keys(
        Point3::new(0.05, 0.05, 0.05),
        Point3::new(2.05, 0.05, 0.05),
        &mut corridor,
    );
    for key in corridor.as_slice().to_vec() {
        tree.update_node(key, false);
    }
    tree
}

#[test]
fn golden_fixture_is_present_and_populated() {
    assert_eq!(rows("raymeta").len(), RAY_CASES.len() + 1);
    assert_eq!(rows("cast").len(), CAST_CASES.len());
    assert!(rows("ray").len() > 500, "key sequences look truncated");
}

#[test]
fn ray_key_sequences_match_reference_exactly() {
    let tree = OcTree::new(0.1).unwrap();
    let mut ray = KeyRay::new();

    for &(name, origin, end) in RAY_CASES {
        let (want_ok, want_count) = golden_ray_meta(name);
        let ok = tree.compute_ray_keys(p(origin), p(end), &mut ray);

        assert_eq!(ok, want_ok, "case {name}: acceptance differs");
        assert_eq!(ray.len(), want_count, "case {name}: key count differs");
        assert_eq!(
            ray.as_slice(),
            golden_ray_keys(name).as_slice(),
            "case {name}: key sequence diverged"
        );
    }
}

#[test]
fn the_ray_cases_actually_cover_the_interesting_shapes() {
    // Guards the test above: if the fixture degenerated into trivial rays the
    // comparison would still pass while covering nothing.
    assert_eq!(golden_ray_meta("same_voxel").1, 0, "degenerate case lost");
    assert!(golden_ray_meta("long").1 > 500, "long ray lost");
    assert!(golden_ray_meta("diagonal").1 > 20, "diagonal lost");
    assert_eq!(
        golden_ray_meta("out_of_bounds"),
        (false, 0),
        "out-of-bounds case lost"
    );
}

#[test]
fn an_out_of_bounds_ray_is_refused_like_the_reference() {
    let tree = OcTree::new(0.1).unwrap();
    let mut ray = KeyRay::new();
    let ok = tree.compute_ray_keys(
        Point3::new(0.0, 0.0, 0.0),
        Point3::new(1.0e9, 0.0, 0.0),
        &mut ray,
    );
    let (want_ok, want_count) = golden_ray_meta("out_of_bounds");
    assert_eq!(ok, want_ok);
    assert_eq!(ray.len(), want_count);
}

#[test]
fn the_oblique_ray_is_asymmetric_in_both_implementations() {
    // Both directions must produce the same *count* but a different sequence.
    // Pinning this keeps someone from "fixing" the asymmetry and silently
    // diverging from C++.
    let forward = golden_ray_keys("oblique");
    let reversed = golden_ray_keys("oblique_reversed");
    assert_eq!(forward.len(), reversed.len());

    let mut f = forward.clone();
    let mut r = reversed.clone();
    f.sort();
    r.sort();
    assert_ne!(f, r, "the reference's oblique rays are not symmetric");
}

#[test]
fn the_cast_scene_matches_reference() {
    assert_counts(&cast_scene(), "cast_scene");
}

#[test]
fn ray_casting_matches_reference() {
    let tree = cast_scene();
    let mut compared = 0usize;

    for &(name, origin, direction, ignore_unknown, max_range) in CAST_CASES {
        let row = rows("cast")
            .into_iter()
            .find(|f| f[1] == name)
            .unwrap_or_else(|| panic!("no cast row for {name:?}"));
        let want_hit = num(row[2]) == 1;
        let want_end = Point3::new(
            f32_from_bits(row[3]),
            f32_from_bits(row[4]),
            f32_from_bits(row[5]),
        );

        let result = tree.cast_ray(p(origin), p(direction), ignore_unknown, max_range);
        assert_eq!(result.is_hit(), want_hit, "case {name}: outcome differs");

        let end = result
            .end()
            .unwrap_or_else(|| panic!("case {name}: no endpoint, expected {want_end:?}"));
        assert_eq!(
            (end.x.to_bits(), end.y.to_bits(), end.z.to_bits()),
            (
                want_end.x.to_bits(),
                want_end.y.to_bits(),
                want_end.z.to_bits()
            ),
            "case {name}: endpoint {end:?} != reference {want_end:?}"
        );
        compared += 1;
    }
    assert_eq!(compared, CAST_CASES.len());
}

#[test]
fn the_cast_cases_cover_both_outcomes() {
    let hits = rows("cast").iter().filter(|f| num(f[2]) == 1).count();
    let misses = rows("cast").iter().filter(|f| num(f[2]) == 0).count();
    assert!(hits > 0 && misses > 0, "{hits} hits, {misses} misses");
}

#[test]
fn insert_ray_matches_reference() {
    let mut tree = OcTree::new(0.1).unwrap();
    tree.insert_ray(
        Point3::new(0.05, 0.05, 0.05),
        Point3::new(1.05, 0.05, 0.05),
        -1.0,
        false,
    );
    assert_counts(&tree, "insert_ray");
    assert_eq!(actual_leaves(&tree), golden_leaves("insert_ray"));

    tree.insert_ray(
        Point3::new(0.05, 0.05, 0.05),
        Point3::new(5.05, 0.05, 0.05),
        1.0,
        false,
    );
    assert_counts(&tree, "insert_ray_truncated");
}

#[test]
fn point_cloud_insertion_matches_reference() {
    let mut tree = OcTree::new(0.1).unwrap();
    tree.insert_point_cloud(&scan(), p(ORIGIN), -1.0, false, false);
    assert_counts(&tree, "cloud_plain");
    assert_eq!(actual_leaves(&tree), golden_leaves("cloud_plain"));
}

#[test]
fn discretized_point_cloud_insertion_matches_reference() {
    let mut tree = OcTree::new(0.1).unwrap();
    tree.insert_point_cloud(&scan(), p(ORIGIN), -1.0, false, true);
    assert_counts(&tree, "cloud_discretized");
    assert_eq!(actual_leaves(&tree), golden_leaves("cloud_discretized"));
}

#[test]
fn max_range_point_cloud_insertion_matches_reference() {
    let mut tree = OcTree::new(0.1).unwrap();
    tree.insert_point_cloud(&scan(), p(ORIGIN), 1.5, false, false);
    assert_counts(&tree, "cloud_maxrange");
    assert_eq!(actual_leaves(&tree), golden_leaves("cloud_maxrange"));
}

#[test]
fn lazy_point_cloud_insertion_matches_reference() {
    let mut tree = OcTree::new(0.1).unwrap();
    tree.insert_point_cloud(&scan(), p(ORIGIN), -1.0, true, false);
    assert_counts(&tree, "cloud_lazy");

    tree.update_inner_occupancy();
    tree.prune();
    assert_counts(&tree, "cloud_lazy_finished");
    assert_eq!(actual_leaves(&tree), golden_leaves("cloud_lazy_finished"));
}

#[test]
fn compute_update_set_sizes_match_reference() {
    let tree = OcTree::new(0.1).unwrap();

    for (kind, discrete) in [("plain", false), ("discrete", true)] {
        let row = rows("update")
            .into_iter()
            .find(|f| f[1] == kind)
            .unwrap_or_else(|| panic!("no update row for {kind:?}"));
        let (want_free, want_occupied) = (num(row[2]) as usize, num(row[3]) as usize);

        let (free, occupied) = if discrete {
            tree.compute_discrete_update(&scan(), p(ORIGIN), -1.0)
        } else {
            tree.compute_update(&scan(), p(ORIGIN), -1.0)
        };

        assert_eq!(free.len(), want_free, "{kind}: free cell count");
        assert_eq!(occupied.len(), want_occupied, "{kind}: occupied cell count");
        for key in &occupied {
            assert!(!free.contains(key), "{kind}: {key:?} is in both sets");
        }
    }
}

#[test]
fn lazy_and_eager_cloud_insertion_agree_once_finished() {
    // Not a reference comparison — an internal consistency check that the
    // lazy path is a pure optimisation, which the fixture also implies.
    let mut eager = OcTree::new(0.1).unwrap();
    eager.insert_point_cloud(&scan(), p(ORIGIN), -1.0, false, false);

    let mut lazy = OcTree::new(0.1).unwrap();
    lazy.insert_point_cloud(&scan(), p(ORIGIN), -1.0, true, false);
    lazy.update_inner_occupancy();
    lazy.prune();

    assert_eq!(actual_leaves(&lazy), actual_leaves(&eager));
}
