//! Differential test: `OctreeCore` structure against OctoMap C++ 1.10.0.
//!
//! The fixture is generated by `scripts/gen_golden_tree.cpp`. It covers node
//! counts, leaf and tree iteration order, and how both change across prune and
//! delete — including deleting a voxel out of a pruned block, which forces the
//! reference to re-expand it.
//!
//! Only *structure* is compared. Node values in the reference are occupancy
//! log-odds; the Rust side uses a plain `u8`, since Phase 3 has no occupancy
//! model. Both sides store one identical value in every leaf so that the
//! pruning predicate behaves the same.

use octomap_core::{OcTreeKey, OctreeCore};

const GOLDEN: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../tests/golden/tree.csv"
));

/// Value stored in every leaf. Any constant works — pruning only needs the
/// siblings to agree.
const LEAF_VALUE: u8 = 1;

fn rows(section: &str) -> Vec<Vec<&'static str>> {
    GOLDEN
        .lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .map(|l| l.split(',').collect::<Vec<_>>())
        .filter(|f| f[0] == section)
        .collect()
}

fn num(s: &str) -> u32 {
    s.parse()
        .unwrap_or_else(|e| panic!("{s:?} is not a number: {e}"))
}

/// The keys the reference inserted, in the order it inserted them.
fn golden_keys() -> Vec<OcTreeKey> {
    let mut rows = rows("key");
    rows.sort_by_key(|f| num(f[1]));
    rows.iter()
        .map(|f| OcTreeKey::new(num(f[2]) as u16, num(f[3]) as u16, num(f[4]) as u16))
        .collect()
}

/// `(size, calc_num_nodes, num_leaf_nodes)` recorded at `stage`.
fn golden_counts(stage: &str) -> (usize, usize, usize) {
    let row = rows("counts")
        .into_iter()
        .find(|f| f[1] == stage)
        .unwrap_or_else(|| panic!("no counts row for stage {stage:?}"));
    (
        num(row[2]) as usize,
        num(row[3]) as usize,
        num(row[4]) as usize,
    )
}

/// `(key, depth)` for each leaf at `stage`, in reference iteration order.
fn golden_leaves(stage: &str) -> Vec<(OcTreeKey, u32)> {
    let mut rows: Vec<_> = rows("leaf").into_iter().filter(|f| f[1] == stage).collect();
    rows.sort_by_key(|f| num(f[2]));
    rows.iter()
        .map(|f| {
            (
                OcTreeKey::new(num(f[3]) as u16, num(f[4]) as u16, num(f[5]) as u16),
                num(f[6]),
            )
        })
        .collect()
}

/// Builds the same tree the reference built, before any prune or delete.
fn build_tree() -> OctreeCore<u8> {
    let mut tree = OctreeCore::new(0.1).unwrap();
    for key in golden_keys() {
        tree.insert(key, LEAF_VALUE);
    }
    tree
}

fn actual_leaves(tree: &OctreeCore<u8>) -> Vec<(OcTreeKey, u32)> {
    tree.iter_leaves().map(|v| (v.key(), v.depth())).collect()
}

fn assert_counts(tree: &OctreeCore<u8>, stage: &str) {
    let (size, calc, leaves) = golden_counts(stage);
    assert_eq!(tree.len(), size, "node count at stage {stage:?}");
    assert_eq!(
        tree.count_nodes(),
        calc,
        "recomputed node count at stage {stage:?}"
    );
    assert_eq!(
        tree.count_leaf_nodes(),
        leaves,
        "leaf count at stage {stage:?}"
    );
}

#[test]
fn golden_fixture_is_present_and_populated() {
    assert!(
        golden_keys().len() > 20,
        "expected a substantial key set, got {}",
        golden_keys().len()
    );
    for stage in [
        "inserted",
        "pruned",
        "deleted_from_pruned_block",
        "deleted_singleton",
    ] {
        golden_counts(stage);
    }
}

#[test]
fn the_key_set_contains_a_duplicate() {
    // The reference inserted 42 keys but reports 41 leaves. Keeping that
    // duplicate is deliberate: re-inserting an existing key must not add nodes,
    // and this is where that gets exercised against C++.
    let keys = golden_keys();
    let unique: std::collections::HashSet<_> = keys.iter().collect();
    assert!(
        unique.len() < keys.len(),
        "fixture lost its duplicate key: {} keys, {} unique",
        keys.len(),
        unique.len()
    );
    assert_eq!(unique.len(), golden_counts("inserted").2);
}

#[test]
fn insertion_produces_the_reference_structure() {
    assert_counts(&build_tree(), "inserted");
}

#[test]
fn leaf_iteration_order_matches_reference_after_insertion() {
    let tree = build_tree();
    assert_eq!(actual_leaves(&tree), golden_leaves("inserted"));
}

#[test]
fn tree_iteration_order_matches_reference() {
    let tree = build_tree();
    let expected: Vec<(OcTreeKey, u32, bool)> = {
        let mut rows: Vec<_> = rows("node")
            .into_iter()
            .filter(|f| f[1] == "inserted")
            .collect();
        rows.sort_by_key(|f| num(f[2]));
        rows.iter()
            .map(|f| {
                (
                    OcTreeKey::new(num(f[3]) as u16, num(f[4]) as u16, num(f[5]) as u16),
                    num(f[6]),
                    num(f[7]) == 1,
                )
            })
            .collect()
    };

    let actual: Vec<(OcTreeKey, u32, bool)> = tree
        .iter_nodes()
        .map(|v| (v.key(), v.depth(), !v.node().has_children()))
        .collect();

    assert_eq!(actual.len(), expected.len(), "node count differs");
    assert_eq!(actual, expected, "tree iteration diverged from reference");
}

#[test]
fn prune_produces_the_reference_structure() {
    let mut tree = build_tree();
    let before = tree.len();
    let removed = tree.prune();

    assert_counts(&tree, "pruned");
    assert_eq!(
        tree.len(),
        before - removed,
        "prune's return value disagrees with the node count"
    );
    assert_eq!(actual_leaves(&tree), golden_leaves("pruned"));
}

#[test]
fn deleting_from_a_pruned_block_matches_reference() {
    let mut tree = build_tree();
    tree.prune();

    // The reference deletes exactly this key, which sits inside the block that
    // pruning merged. Descending into it must re-expand the block.
    assert!(tree.delete(OcTreeKey::new(32768, 32768, 32768)));

    assert_counts(&tree, "deleted_from_pruned_block");
    assert_eq!(
        actual_leaves(&tree),
        golden_leaves("deleted_from_pruned_block")
    );
}

#[test]
fn deleting_a_singleton_collapses_its_ancestry_like_the_reference() {
    let mut tree = build_tree();
    tree.prune();
    tree.delete(OcTreeKey::new(32768, 32768, 32768));
    assert!(tree.delete(OcTreeKey::new(32768 + 5000, 32768, 32768 - 5000)));

    assert_counts(&tree, "deleted_singleton");
}

#[test]
fn depth_limited_leaf_iteration_matches_reference() {
    let mut tree = build_tree();
    tree.prune();
    tree.delete(OcTreeKey::new(32768, 32768, 32768));
    tree.delete(OcTreeKey::new(32768 + 5000, 32768, 32768 - 5000));

    let mut compared = 0usize;
    for max_depth in [2u32, 6, 10, 14] {
        let mut expected: Vec<_> = rows("leaf_depth")
            .into_iter()
            .filter(|f| num(f[1]) == max_depth)
            .collect();
        expected.sort_by_key(|f| num(f[2]));
        let expected: Vec<(OcTreeKey, u32)> = expected
            .iter()
            .map(|f| {
                (
                    OcTreeKey::new(num(f[3]) as u16, num(f[4]) as u16, num(f[5]) as u16),
                    num(f[6]),
                )
            })
            .collect();

        assert!(
            !expected.is_empty(),
            "fixture has no depth-{max_depth} rows"
        );

        let actual: Vec<(OcTreeKey, u32)> = tree
            .iter_leaves_to_depth(max_depth)
            .map(|v| (v.key(), v.depth()))
            .collect();

        assert_eq!(actual, expected, "depth-limited view at {max_depth}");
        compared += 1;
    }
    assert_eq!(compared, 4);
}
