//! Differential test: the occupancy model against OctoMap C++ 1.10.0.
//!
//! The fixture is generated by `scripts/gen_golden_occupancy.cpp`. Log-odds are
//! compared as raw IEEE-754 **bit patterns**, so a one-ULP divergence in the
//! update arithmetic shows up as a failure instead of hiding behind decimal
//! formatting.

use octomap_core::{OcTree, OcTreeKey};

const GOLDEN: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../tests/golden/occupancy.csv"
));

/// Key-space coordinate of the world origin.
const C: u16 = 32768;

fn rows(section: &str) -> Vec<Vec<&'static str>> {
    GOLDEN
        .lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .map(|l| l.split(',').collect::<Vec<_>>())
        .filter(|f| f[0] == section)
        .collect()
}

fn num(s: &str) -> u64 {
    s.parse()
        .unwrap_or_else(|e| panic!("{s:?} is not a number: {e}"))
}

fn bits(s: &str) -> u32 {
    num(s) as u32
}

/// Offsets the reference used to build its mixed scene, with the occupancy flag.
const SCENE: &[(i32, i32, i32, bool)] = &[
    (0, 0, 0, true),
    (1, 0, 0, false),
    (0, 1, 0, true),
    (5, 5, 5, false),
    (5, 5, 6, false),
    (-3, -3, -3, true),
    (100, 0, 0, true),
    (100, 0, 0, true),
    (100, 0, 0, false),
    (7, 7, 7, false),
    (7, 7, 7, false),
    (7, 7, 7, true),
];

fn offset_key(dx: i32, dy: i32, dz: i32) -> OcTreeKey {
    OcTreeKey::new(
        (C as i32 + dx) as u16,
        (C as i32 + dy) as u16,
        (C as i32 + dz) as u16,
    )
}

fn build_scene() -> OcTree {
    let mut tree = OcTree::new(0.1).unwrap();
    for &(dx, dy, dz, occupied) in SCENE {
        tree.update_node(offset_key(dx, dy, dz), occupied);
    }
    tree
}

fn golden_counts(stage: &str) -> (usize, usize) {
    let row = rows("counts")
        .into_iter()
        .find(|f| f[1] == stage)
        .unwrap_or_else(|| panic!("no counts row for stage {stage:?}"));
    (num(row[2]) as usize, num(row[3]) as usize)
}

fn golden_rootval(stage: &str) -> u32 {
    let row = rows("rootval")
        .into_iter()
        .find(|f| f[1] == stage)
        .unwrap_or_else(|| panic!("no rootval row for stage {stage:?}"));
    bits(row[2])
}

/// `(key, depth, log-odds bits)` per leaf at `stage`, in reference order.
fn golden_leaves(stage: &str) -> Vec<(OcTreeKey, u32, u32)> {
    let mut rows: Vec<_> = rows("leaf").into_iter().filter(|f| f[1] == stage).collect();
    rows.sort_by_key(|f| num(f[2]));
    rows.iter()
        .map(|f| {
            (
                OcTreeKey::new(num(f[3]) as u16, num(f[4]) as u16, num(f[5]) as u16),
                num(f[6]) as u32,
                bits(f[7]),
            )
        })
        .collect()
}

fn actual_leaves(tree: &OcTree) -> Vec<(OcTreeKey, u32, u32)> {
    tree.iter_leaves()
        .map(|v| (v.key(), v.depth(), v.value().log_odds.to_bits()))
        .collect()
}

fn assert_counts(tree: &OcTree, stage: &str) {
    let (size, leaves) = golden_counts(stage);
    assert_eq!(tree.len(), size, "node count at stage {stage:?}");
    assert_eq!(
        tree.count_leaf_nodes(),
        leaves,
        "leaf count at stage {stage:?}"
    );
    assert_eq!(
        tree.count_nodes(),
        tree.len(),
        "incremental node count drifted at stage {stage:?}"
    );
}

#[test]
fn golden_fixture_is_present_and_populated() {
    assert!(rows("seq").len() >= 40, "sequence section looks short");
    for stage in [
        "eager_block",
        "reopened",
        "lazy_inserted",
        "lazy_pruned",
        "scene",
        "max_likelihood",
    ] {
        golden_counts(stage);
    }
}

#[test]
fn update_sequence_matches_reference_bit_for_bit() {
    let mut tree = OcTree::new(0.1).unwrap();
    let key = OcTreeKey::new(C, C, C);

    let mut compared = 0usize;
    for row in rows("seq") {
        let step = num(row[1]);
        let occupied = num(row[2]) == 1;
        let want_bits = bits(row[3]);
        let want_size = num(row[4]) as usize;

        let got = tree.update_node(key, occupied);
        assert_eq!(
            got.to_bits(),
            want_bits,
            "step {step}: log-odds diverged (got {got}, want {})",
            f32::from_bits(want_bits)
        );
        assert_eq!(tree.len(), want_size, "step {step}: node count diverged");
        compared += 1;
    }
    assert_eq!(compared, 43, "the fixture plan is 12+3+6+20+2 steps");
}

#[test]
fn the_sequence_actually_reaches_both_clamps() {
    // Guards the test above: if the fixture stopped saturating, the comparison
    // would still pass while no longer covering the clamping path.
    let sensor = *OcTree::new(0.1).unwrap().sensor();
    let seen: Vec<f32> = rows("seq")
        .iter()
        .map(|r| f32::from_bits(bits(r[3])))
        .collect();
    assert!(
        seen.iter().any(|&l| l == sensor.clamping_thres_max()),
        "sequence never hits the upper clamp"
    );
    assert!(
        seen.iter().any(|&l| l == sensor.clamping_thres_min()),
        "sequence never hits the lower clamp"
    );
}

#[test]
fn set_node_value_clamping_matches_reference() {
    let mut tree = OcTree::new(0.1).unwrap();
    let mut compared = 0usize;
    for (i, row) in rows("setval").iter().enumerate() {
        let input = f32::from_bits(bits(row[1]));
        let want = bits(row[2]);
        let key = OcTreeKey::new(C + i as u16, C, C);

        let got = tree.set_node_value(key, input, false);
        assert_eq!(got.to_bits(), want, "set_node_value({input})");
        compared += 1;
    }
    assert!(compared >= 8, "only {compared} values compared");
}

#[test]
fn eager_insertion_auto_prunes_like_the_reference() {
    let mut tree = OcTree::new(0.1).unwrap();
    for dx in 0..2u16 {
        for dy in 0..2u16 {
            for dz in 0..2u16 {
                tree.update_node(OcTreeKey::new(C + dx, C + dy, C + dz), true);
            }
        }
    }
    assert_counts(&tree, "eager_block");
    assert_eq!(actual_leaves(&tree), golden_leaves("eager_block"));
}

#[test]
fn updating_inside_a_pruned_block_reopens_it_like_the_reference() {
    let mut tree = OcTree::new(0.1).unwrap();
    for dx in 0..2u16 {
        for dy in 0..2u16 {
            for dz in 0..2u16 {
                tree.update_node(OcTreeKey::new(C + dx, C + dy, C + dz), true);
            }
        }
    }
    tree.update_node(OcTreeKey::new(C, C, C), false);

    assert_counts(&tree, "reopened");
    assert_eq!(actual_leaves(&tree), golden_leaves("reopened"));
}

#[test]
fn lazy_insertion_matches_reference() {
    let mut tree = OcTree::new(0.1).unwrap();
    let hit = tree.sensor().prob_hit_log();
    for dx in 0..2u16 {
        for dy in 0..2u16 {
            for dz in 0..2u16 {
                tree.update_node_log_odds(OcTreeKey::new(C + dx, C + dy, C + dz), hit, true);
            }
        }
    }
    assert_counts(&tree, "lazy_inserted");
    assert_eq!(
        tree.core().root().unwrap().value().log_odds.to_bits(),
        golden_rootval("lazy_inserted"),
        "lazy insertion must leave the root untouched"
    );

    tree.update_inner_occupancy();
    assert_eq!(
        tree.core().root().unwrap().value().log_odds.to_bits(),
        golden_rootval("after_inner_update")
    );

    tree.prune();
    assert_counts(&tree, "lazy_pruned");
}

#[test]
fn mixed_scene_matches_reference() {
    let tree = build_scene();
    assert_counts(&tree, "scene");
    assert_eq!(actual_leaves(&tree), golden_leaves("scene"));
    assert_eq!(
        tree.core().root().unwrap().value().log_odds.to_bits(),
        golden_rootval("scene"),
        "inner-node propagation diverged at the root"
    );
}

#[test]
fn max_likelihood_matches_reference() {
    let mut tree = build_scene();
    tree.to_max_likelihood();

    assert_counts(&tree, "max_likelihood");
    assert_eq!(actual_leaves(&tree), golden_leaves("max_likelihood"));
}

#[test]
fn max_likelihood_leaves_only_the_two_clamps() {
    // Sanity check on the fixture: after the collapse every leaf must sit on
    // one clamp or the other, or the comparison above is not testing much.
    let sensor = *OcTree::new(0.1).unwrap().sensor();
    let leaves = golden_leaves("max_likelihood");
    assert!(!leaves.is_empty());
    for (key, _, b) in leaves {
        let l = f32::from_bits(b);
        assert!(
            l == sensor.clamping_thres_max() || l == sensor.clamping_thres_min(),
            "leaf {key:?} sits at {l}, neither clamp"
        );
    }
}

#[test]
fn change_detection_records_the_same_keys_as_reference() {
    let mut tree = OcTree::new(0.1).unwrap();
    tree.enable_change_detection(true);
    tree.update_node(OcTreeKey::new(C, C, C), true);
    tree.update_node(OcTreeKey::new(C + 50, C, C), false);

    let mut actual: Vec<(u16, u16, u16, bool)> = tree
        .changed_keys()
        .iter()
        .map(|(k, &is_new)| (k.x(), k.y(), k.z(), is_new))
        .collect();
    actual.sort();

    let expected: Vec<(u16, u16, u16, bool)> = rows("changed")
        .iter()
        .filter(|f| f[1] == "fresh")
        .map(|f| {
            (
                num(f[2]) as u16,
                num(f[3]) as u16,
                num(f[4]) as u16,
                num(f[5]) == 1,
            )
        })
        .collect();

    assert!(!expected.is_empty(), "fixture has no changed-key rows");
    assert_eq!(actual, expected);
}

#[test]
fn change_detection_flip_and_flip_back_match_reference() {
    let counts: std::collections::HashMap<&str, usize> = rows("changed_count")
        .iter()
        .map(|f| (f[1], num(f[2]) as usize))
        .collect();

    let mut tree = OcTree::new(0.1).unwrap();
    tree.enable_change_detection(true);
    tree.update_node(OcTreeKey::new(C, C, C), true);
    tree.update_node(OcTreeKey::new(C + 50, C, C), false);
    tree.reset_change_detection();

    tree.update_node(OcTreeKey::new(C + 50, C, C), true);
    assert_eq!(
        tree.changed_key_count(),
        counts["after_flip"],
        "flipping an existing voxel should register one change"
    );

    tree.update_node(OcTreeKey::new(C + 50, C, C), false);
    tree.update_node(OcTreeKey::new(C + 50, C, C), false);
    assert_eq!(
        tree.changed_key_count(),
        counts["after_flip_back"],
        "flipping back should cancel the change"
    );
}
